plugins {
    id 'java'
    id 'net.neoforged.gradle.userdev' version '7.0.145'
}

version = '1.0.0'
group = 'com.mgmod.mgmod'

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

runs {
    client {
        client()
        systemProperty 'neoforge.enabledGameTestNamespaces', 'mgmod'
    }
    server {
        server()
        programArgument '--nogui'
        systemProperty 'neoforge.enabledGameTestNamespaces', 'mgmod'
    }
}

dependencies {
    implementation "net.neoforged:neoforge:21.1.172"
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [minecraft_version: '1.21.1', neoforge_version: '21.1.172', mod_id: 'mgmod', mod_version: version]
    inputs.properties replaceProperties
    filesMatching(['META-INF/mods.toml', 'META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}
